### PR TITLE
Save documentation and examples

### PR DESCRIPTION
**Pull request by dmiddleton**
Saves the documentation and examples after the gorbachev build

### CODE REVIEW

**Comment by dmiddleton** [comment]
Thanks Ed, that all worked very smoothly!

How convinced are you that the current examples (esp. of the less frequent types such as theses and tech reports) meet MPI's current style requirements?

**Comment by dmiddleton** [comment]
Sorry that was a horribly open question.  I'll work on some changes to thesis formatting then talk!

**Comment by edwardabraham** [comment]
I am not totally convinced. Have worked through some cases, and have
covered off theses, but the tech-reports I usually do as unpublished. This
lets me fiddle with the notes to get things in the format that Barbara
needs. We have just had four reports go through, so it has had quite a bit
of a workout lately.
Here is a little summary of our bibliography:

1057 @Article{
 147 @Book{
   1 @Conference{
  92 @InCollection{
  15 @InProceedings{
   7 @Manual{
  54 @Misc{
  17 @PhDThesis{
   3 @TechReport{
 265 @Unpublished{

I would guess that the Conference, Manual, InProceedings, and TechReport
entries should be translated into more frequently used styles! Not sure
what Misc is either!

**Comment by dmiddleton** [comment]
Your PhDThesis example puts parenthesis around type+institution e.g. (Doctoral dissertation, The University of Auckland, Auckland, New Zealand).  I've been asked to remove the parenthesis (for a Masters thesis). 

Did any of the recent four cite a thesis?  If not, I'll fix....

**Comment by edwardabraham** [comment]
By all means have a go at fixing this (for both theses types, I presume). I
find the lines in
https://github.com/plk/biblatex-apa/blob/master/tex/latex/biblatex-apa/bbx/apa.bbx
that
need modifying, and then use the `xpatch` mechanisms to make the fix. You
should be able to follow other fixes in the `dtx` file.

**Pull request merged**
